[package]
name = "tweakria2"
description = "A tool that use for tweak aria2."
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18.3"
tempfile = "3.10.1"
thiserror = "1.0.58"
